<?= $this->extend('layout') ?><?= $this->section('content') ?>
<?php $canEdit=\App\Services\Access::can((int)auth()->id(),'clientes.editar'); ?>
<div class="page-heading"><div><p class="eyebrow mb-2">Directorio</p><h1 class="text-3xl font-semibold">Clientes</h1><p class="text-base-content/65 mt-2">Información de contacto, identificación y estado.</p></div><?php if (\App\Services\Access::can((int)auth()->id(),'clientes.crear')): ?><a class="btn btn-primary" href="<?= site_url('clientes/nuevo') ?>"><i data-lucide="plus" class="icon" aria-hidden="true"></i>Nuevo cliente</a><?php endif ?></div>
<div class="panel"><form method="get" class="p-5 flex flex-wrap gap-3 border-b border-base-300"><label class="input flex-1 min-w-40"><i data-lucide="search" class="icon" aria-hidden="true"></i><input name="q" value="<?= esc($q,'attr') ?>" aria-label="Buscar por nombre o identificación" placeholder="Buscar por nombre o identificación" maxlength="100"></label><select name="estado" aria-label="Estado" class="select w-auto"><option value="">Todos los estados</option><option value="1" <?= $status==='1'?'selected':'' ?>>Activos</option><option value="0" <?= $status==='0'?'selected':'' ?>>Inactivos</option></select><button class="btn" type="submit">Buscar</button></form>
<?php if (!$rows): ?><div class="empty"><i data-lucide="users" class="w-10 h-10 mx-auto mb-4 text-base-content/40" aria-hidden="true"></i><h2 class="text-xl font-semibold">No hay clientes para mostrar</h2><p class="mt-2 text-base-content/65">Registra un cliente o ajusta los filtros de búsqueda.</p></div>
<?php else: ?><div class="overflow-x-auto"><table class="table"><caption class="sr-only">Directorio de clientes</caption><thead><tr><th>Cliente</th><th>Identificación</th><th>Estado</th><th><span class="sr-only">Acciones</span></th></tr></thead><tbody>
<?php foreach ($rows as $row): ?><tr><td><div class="font-semibold"><?= esc($row['nombre']) ?></div><span class="text-xs text-base-content/55">Cliente #<?= $row['id'] ?></span></td><td><?= esc($row['identificacion'] ?: 'No informada') ?></td><td><span class="badge <?= $row['activo']?'badge-success badge-soft':'badge-ghost' ?>"><?= $row['activo']?'Activo':'Inactivo' ?></span></td><td><?php if ($canEdit): ?><a class="btn btn-ghost btn-sm" href="<?= site_url('clientes/'.$row['id']) ?>">Editar<span class="sr-only"> <?= esc($row['nombre']) ?></span></a><?php endif ?></td></tr><?php endforeach ?>
</tbody></table></div><?php endif ?>
<?= view('partials/pagination',['total'=>$total,'page'=>$page,'base'=>'clientes','params'=>['q'=>$q,'estado'=>$status]]) ?></div>
<?= $this->endSection() ?>
