<!doctype html><html lang="es"><head><meta charset="utf-8"><style>
@page{margin:34px 42px}body{color:#172033;font-family:"DejaVu Sans",sans-serif;font-size:11px;line-height:1.45}h1,h2,p{margin:0}h1{font-size:24px}h2{font-size:13px;margin-bottom:8px}.top{border-bottom:2px solid #172033;padding-bottom:16px}.brand{font-size:16px;font-weight:bold}.copy{color:#42526b;float:right;font-size:12px;font-weight:bold;letter-spacing:1px}.meta{margin-top:18px;width:100%}.meta td{padding:2px 0;vertical-align:top;width:50%}.label{color:#637083;font-size:9px;text-transform:uppercase}.panel{border:1px solid #d9dee8;margin-top:18px;padding:13px}table.data{border-collapse:collapse;margin-top:8px;width:100%}table.data th{background:#edf1f6;font-size:9px;padding:7px;text-align:left;text-transform:uppercase}table.data td{border-bottom:1px solid #e2e6ed;padding:7px;vertical-align:top}.right{text-align:right!important}.totals{margin-left:55%;margin-top:16px;width:45%}.totals td{padding:4px 0}.total{border-top:1px solid #172033;font-weight:bold}.reversed{background:#fee2e2;border:2px solid #b91c1c;color:#7f1d1d;font-size:14px;font-weight:bold;margin-top:16px;padding:10px;text-align:center}.footer{color:#637083;margin-top:28px;text-align:center}
</style></head><body><?php $snapshot = $receipt['snapshot']; ?>
<div class="top"><span class="copy">COPIA</span><p class="brand"><?= esc($snapshot['business']['name']) ?></p><h1>RECIBO <?= esc($receipt['code']) ?></h1><?php if ($snapshot['business']['identification']): ?><p><?= esc($snapshot['business']['identification']) ?></p><?php endif ?></div>
<?php if ($receipt['payment_status'] === 'REVERTIDO'): ?><div class="reversed">PAGO REVERTIDO<br><span style="font-size:10px;font-weight:normal"><?= esc((string) $receipt['reversal_reason']) ?> · <?= esc((string) $receipt['reversed_at']) ?></span></div><?php endif ?>
<table class="meta"><tr><td><div class="label">Cliente</div><strong><?= esc($snapshot['client']['name']) ?></strong><br><?= esc((string) $snapshot['client']['identification']) ?></td><td><div class="label">Emitido</div><?= esc($snapshot['issued_at']) ?><br>Responsable: <?= esc($snapshot['responsible']) ?></td></tr></table>
<div class="panel"><h2>Pago recibido</h2><table class="data"><thead><tr><th>Medio / referencia</th><th>Cuenta</th><th>Fecha</th><th class="right">Importe</th></tr></thead><tbody><?php foreach ($snapshot['payments'] as $payment): ?><tr><td><?= esc($payment['method']) ?><br><?= esc($payment['reference']) ?></td><td><?= esc($payment['institution']) ?><br><?= esc($payment['account_alias']) ?></td><td><?= esc($payment['bank_date'] ?: $payment['declared_on']) ?></td><td class="right">$<?= esc($payment['amount']) ?></td></tr><?php endforeach ?></tbody></table></div>
<div class="panel"><h2>Aplicaciones al emitir</h2><?php if (!$snapshot['applications']): ?><p>Sin aplicaciones a cuotas.</p><?php else: ?><table class="data"><thead><tr><th>Documento</th><th>Cuota</th><th>Concepto</th><th class="right">Aplicado</th></tr></thead><tbody><?php foreach ($snapshot['applications'] as $application): ?><tr><td><?= esc($application['document']) ?></td><td><?= (int) $application['installment_number'] ?></td><td><?= esc($application['concept']) ?></td><td class="right">$<?= esc($application['amount']) ?></td></tr><?php endforeach ?></tbody></table><?php endif ?></div>
<table class="totals"><tr><td>Recibido</td><td class="right">$<?= esc($snapshot['total']) ?></td></tr><tr><td>Aplicado</td><td class="right">$<?= esc($snapshot['applied']) ?></td></tr><tr class="total"><td>Disponible</td><td class="right">$<?= esc($snapshot['available']) ?></td></tr></table><div class="footer"><p><?= esc($snapshot['business']['footer']) ?></p><p>Documento interno. No constituye comprobante tributario.</p></div>
</body></html>
