<?= $this->extend('layouts/app') ?>
<?= $this->section('content') ?>

<?php
$rows = $rows ?? [];
$filters = $filters ?? ['q' => '', 'desde' => '', 'hasta' => '', 'estado' => '', 'origen' => '', 'medio' => '', 'page' => 1];
$summary = $summary ?? ['amount' => '0.00', 'confirmed' => 0, 'reversed' => 0];
$exportParams = array_filter([
    'q' => $filters['q'], 'desde' => $filters['desde'], 'hasta' => $filters['hasta'],
    'estado' => $filters['estado'], 'origen' => $filters['origen'], 'medio' => $filters['medio'],
], static fn (string $value): bool => $value !== '');
$exportQuery = $exportParams ? '?' . http_build_query($exportParams) : '';
?>

<?= view('partials/page_header', [
    'context' => 'Reportes financieros',
    'title' => $title,
    'description' => $description,
    'primaryAction' => $total > 0 ? ['label' => 'Descargar CSV', 'url' => site_url('reportes/pagos.csv') . $exportQuery, 'icon' => 'download'] : null,
], ['saveData' => false]) ?>

<nav class="mb-6 overflow-x-auto" aria-label="Navegación de reportes"><div class="tabs tabs-box w-max min-w-full sm:min-w-0"><a class="tab" href="<?= site_url('reportes') ?>"><i data-lucide="chart-no-axes-combined" class="icon" aria-hidden="true"></i>Resumen</a><a class="tab" href="<?= site_url('reportes/cartera') ?>"><i data-lucide="wallet" class="icon" aria-hidden="true"></i>Cartera</a><a class="tab tab-active" aria-current="page" href="<?= site_url('reportes/pagos') ?>"><i data-lucide="receipt" class="icon" aria-hidden="true"></i>Pagos</a></div></nav>

<form class="card card-border mb-6 bg-base-100" method="get" action="<?= site_url('reportes/pagos') ?>"><div class="card-body gap-4"><div class="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><fieldset class="fieldset"><legend class="fieldset-legend">Buscar</legend><input class="input w-full" type="search" name="q" maxlength="100" value="<?= esc($filters['q'], 'attr') ?>" placeholder="Cliente o referencia"></fieldset><fieldset class="fieldset"><legend class="fieldset-legend">Desde</legend><input class="input w-full" type="date" name="desde" value="<?= esc($filters['desde'], 'attr') ?>"></fieldset><fieldset class="fieldset"><legend class="fieldset-legend">Hasta</legend><input class="input w-full" type="date" name="hasta" value="<?= esc($filters['hasta'], 'attr') ?>"></fieldset><fieldset class="fieldset"><legend class="fieldset-legend">Estado</legend><select class="select w-full" name="estado"><option value="">Todos</option><option value="confirmado" <?= $filters['estado'] === 'confirmado' ? 'selected' : '' ?>>Confirmado</option><option value="revertido" <?= $filters['estado'] === 'revertido' ? 'selected' : '' ?>>Revertido</option></select></fieldset><fieldset class="fieldset"><legend class="fieldset-legend">Origen</legend><select class="select w-full" name="origen"><option value="">Todos</option><option value="OPERATIVO" <?= $filters['origen'] === 'OPERATIVO' ? 'selected' : '' ?>>Operativo</option><option value="HISTORICO" <?= $filters['origen'] === 'HISTORICO' ? 'selected' : '' ?>>Histórico</option><option value="APERTURA" <?= $filters['origen'] === 'APERTURA' ? 'selected' : '' ?>>Apertura</option></select></fieldset><fieldset class="fieldset"><legend class="fieldset-legend">Medio</legend><select class="select w-full" name="medio"><option value="">Todos</option><option value="TRANSFERENCIA" <?= $filters['medio'] === 'TRANSFERENCIA' ? 'selected' : '' ?>>Transferencia</option><option value="DEPOSITO" <?= $filters['medio'] === 'DEPOSITO' ? 'selected' : '' ?>>Depósito</option><option value="EFECTIVO" <?= $filters['medio'] === 'EFECTIVO' ? 'selected' : '' ?>>Efectivo</option></select></fieldset></div><div class="card-actions justify-end"><a class="btn" href="<?= site_url('reportes/pagos') ?>">Limpiar</a><button class="btn btn-primary" type="submit"><i data-lucide="search" class="icon" aria-hidden="true"></i>Filtrar</button></div></div></form>

<section class="stats stats-vertical w-full border border-base-300 bg-base-100 md:stats-horizontal" aria-label="Resumen de pagos"><div class="stat"><div class="stat-title">Importe filtrado</div><div class="stat-value font-data text-3xl">$<?= number_format((float) $summary['amount'], 2) ?></div><div class="stat-desc"><span class="font-data"><?= (int) $total ?></span> movimientos</div></div><div class="stat"><div class="stat-title">Confirmados</div><div class="stat-value font-data text-3xl"><?= (int) $summary['confirmed'] ?></div><div class="stat-desc">Cobros vigentes</div></div><div class="stat"><div class="stat-title">Revertidos</div><div class="stat-value font-data text-3xl"><?= (int) $summary['reversed'] ?></div><div class="stat-desc">Conservados para trazabilidad</div></div></section>

<section class="card card-border mt-6 bg-base-100" aria-labelledby="payments-report-title"><div class="card-body p-0"><header class="section-heading"><div><p class="eyebrow mb-2">Corte de recaudo</p><h2 id="payments-report-title" class="card-title">Pagos por estado</h2><p class="mt-1 text-sm text-base-content/70">Exporta el corte filtrado o abre un pago para revisar su aplicación.</p></div><?php if ($total > 0): ?><div class="join"><a class="btn join-item" href="<?= esc(site_url('reportes/pagos.csv') . $exportQuery, 'attr') ?>">CSV</a><a class="btn join-item" href="<?= esc(site_url('reportes/pagos.xlsx') . $exportQuery, 'attr') ?>">XLSX</a></div><?php endif ?></header>
<?php if (!$rows): ?>
<?= view('partials/empty_state', ['icon' => 'receipt', 'title' => 'No hay pagos para reportar', 'description' => 'No existen movimientos confirmados o revertidos que coincidan con los filtros.'], ['saveData' => false]) ?>
<?php else: ?>
<div class="hidden overflow-x-auto md:block"><table class="table"><caption class="sr-only">Reporte de pagos por estado</caption><thead><tr><th scope="col">Pago</th><th scope="col">Cliente</th><th scope="col">Fecha</th><th scope="col">Importe</th><th scope="col">Aplicado</th><th scope="col">Disponible</th><th scope="col">Origen y medio</th><th scope="col">Estado</th><th scope="col"><span class="sr-only">Acción</span></th></tr></thead><tbody><?php foreach ($rows as $row): ?><tr><th scope="row" class="font-data">#<?= (int) $row['id'] ?></th><td><?= esc($row['cliente']) ?></td><td class="font-data whitespace-nowrap"><?= esc($row['fecha']) ?></td><td class="font-data">$<?= number_format((float) $row['importe'], 2) ?></td><td class="font-data">$<?= number_format((float) $row['aplicado'], 2) ?></td><td class="font-data">$<?= number_format((float) $row['disponible'], 2) ?></td><td><span class="block"><?= esc($row['origen_label']) ?></span><span class="text-xs text-base-content/70"><?= esc($row['medio_label']) ?></span></td><td><span class="badge <?= $row['estado'] === 'Confirmado' ? 'badge-success badge-soft' : 'badge-error badge-soft' ?>"><?= esc($row['estado']) ?></span></td><td class="text-right"><a class="btn btn-sm" href="<?= site_url('pagos/' . (int) $row['id']) ?>">Abrir</a></td></tr><?php endforeach ?></tbody></table></div>
<ul class="divide-y divide-base-300 md:hidden" aria-label="Reporte de pagos por estado"><?php foreach ($rows as $row): ?><li class="record-card"><div class="min-w-0"><p class="font-semibold">#<?= (int) $row['id'] ?> · <?= esc($row['cliente']) ?></p><p class="font-data mt-1 text-sm text-base-content/70"><?= esc($row['fecha']) ?> · $<?= number_format((float) $row['importe'], 2) ?></p><p class="mt-1 text-xs text-base-content/70"><?= esc($row['origen_label']) ?> · <?= esc($row['medio_label']) ?></p></div><div class="flex flex-col items-end gap-2"><span class="badge <?= $row['estado'] === 'Confirmado' ? 'badge-success badge-soft' : 'badge-error badge-soft' ?>"><?= esc($row['estado']) ?></span><a class="btn btn-sm" href="<?= site_url('pagos/' . (int) $row['id']) ?>">Abrir</a></div></li><?php endforeach ?></ul>
<?= view('partials/pagination', ['total' => $total, 'page' => $page, 'pageSize' => $pageSize, 'base' => 'reportes/pagos', 'params' => $exportParams], ['saveData' => false]) ?>
<?php endif ?></div></section>

<?= $this->endSection() ?>
