<?= $this->extend('layouts/app') ?>
<?= $this->section('content') ?>

<?php
$mode = $mode ?? 'index';
$statusClass = static fn (string $status): string => match ($status) {
    'Aprobado', 'Vinculado' => 'badge-success badge-soft',
    'Rechazado' => 'badge-error badge-soft',
    'Reabierto' => 'badge-info badge-soft',
    default => 'badge-warning badge-soft',
};
?>

<?= view('partials/page_header', [
    'context' => 'Comprobantes bancarios', 'title' => $title, 'description' => $description,
    'primaryAction' => match ($mode) {
        'create', 'detail', 'unknown' => ['label' => 'Ver comprobantes', 'url' => site_url('reportes-pago'), 'icon' => 'list'],
        default => ['label' => 'Registrar comprobante', 'url' => site_url('reportes-pago/nuevo'), 'icon' => 'upload'],
    },
], ['saveData' => false]) ?>

<?php if ($mode === 'create'): ?>
<form method="post" enctype="multipart/form-data" action="<?= site_url('reportes-pago') ?>" class="card card-border bg-base-100"><div class="card-body">
<?= csrf_field() ?><input type="hidden" name="idempotency_key" value="<?= esc($idempotencyKey, 'attr') ?>">
<div class="alert alert-info alert-soft mb-4"><i data-lucide="info" class="icon" aria-hidden="true"></i><span>Registrar evidencia no crea un cobro ni reduce la deuda. Un usuario autorizado deberá conciliarla.</span></div>
<div class="grid gap-4 sm:grid-cols-2">
<label class="form-field"><span>Monto reportado</span><input class="input w-full" name="monto" type="number" min="0.01" step="0.01" required value="<?= esc(old('monto', ''), 'attr') ?>" placeholder="Ej. 250.00" inputmode="decimal"></label>
<label class="form-field"><span>Fecha bancaria</span><input class="input w-full" name="fecha" type="date" required value="<?= esc(old('fecha', date('Y-m-d')), 'attr') ?>"></label>
<label class="form-field"><span>Método</span><select class="select w-full" name="metodo" required><option value="TRANSFERENCIA" <?= old('metodo', 'TRANSFERENCIA') === 'TRANSFERENCIA' ? 'selected' : '' ?>>Transferencia</option><option value="DEPOSITO" <?= old('metodo') === 'DEPOSITO' ? 'selected' : '' ?>>Depósito</option></select></label>
<label class="form-field"><span>Cuenta receptora</span><select class="select w-full" name="cuenta_bancaria_id" required><option value="">Seleccionar cuenta</option><?php foreach ($bankAccounts as $account): ?><option value="<?= (int) $account['id'] ?>" <?= (string) old('cuenta_bancaria_id', '') === (string) $account['id'] ? 'selected' : '' ?>><?= esc($account['institucion'] . ' · ' . $account['alias'] . ' · ' . $account['numero_cuenta']) ?></option><?php endforeach ?></select></label>
<label class="form-field"><span>Referencia bancaria</span><input class="input w-full" name="referencia" maxlength="120" required value="<?= esc(old('referencia', ''), 'attr') ?>" placeholder="Código de operación"></label>
<label class="form-field"><span>Cliente sugerido (opcional)</span><select class="select w-full" name="cliente_id" data-client-select data-source="<?= site_url('clientes/datos') ?>"><option value="">Dejar sin identificar</option><?php if (old('cliente_id')): ?><option value="<?= (int) old('cliente_id') ?>" selected>Cliente #<?= (int) old('cliente_id') ?></option><?php endif ?></select></label>
<label class="form-field sm:col-span-2"><span>Observaciones</span><textarea class="textarea w-full" name="observacion" maxlength="500" rows="3" placeholder="Información útil para quien revise"><?= esc(old('observacion', '')) ?></textarea></label>
<label class="form-field sm:col-span-2"><span>Evidencia privada (opcional)</span><input class="file-input w-full" type="file" name="attachment" accept=".pdf,.png,.jpg,.jpeg"><span class="text-xs text-base-content/60">PDF, PNG o JPEG; máximo 2 MB.</span></label>
</div><div class="card-actions mt-4 justify-end"><a class="btn" href="<?= site_url('reportes-pago') ?>">Cancelar</a><button class="btn btn-primary" type="submit" <?= !$bankAccounts ? 'disabled' : '' ?>>Registrar comprobante</button></div>
<?php if (!$bankAccounts): ?><p class="text-sm text-error">No existen cuentas bancarias activas. Configura una antes de registrar el comprobante.</p><?php endif ?>
</div></form>

<?php elseif ($mode === 'detail'): ?>
<?php $final = in_array($statement['estado'], ['Aprobado', 'Vinculado'], true); ?>
<section class="card card-border bg-base-100"><div class="card-body"><div class="flex flex-wrap items-center justify-between gap-3"><h2 class="card-title">Comprobante #<?= (int) $statement['id'] ?></h2><span class="badge <?= $statusClass((string) $statement['estado']) ?>"><?= esc($statement['estado']) ?></span></div>
<dl class="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><div><dt class="text-sm text-base-content/70">Monto reportado</dt><dd class="font-data text-lg">$<?= number_format((float) $statement['monto'], 2) ?></dd></div><div><dt class="text-sm text-base-content/70">Cliente</dt><dd><?= esc($statement['cliente'] ?: 'Sin identificar') ?></dd></div><div><dt class="text-sm text-base-content/70">Cuenta receptora</dt><dd><?= esc($statement['banco'] . ' · ' . $statement['cuenta']) ?></dd></div><div><dt class="text-sm text-base-content/70">Método</dt><dd><?= esc(ucfirst(mb_strtolower((string) $statement['metodo']))) ?></dd></div><div><dt class="text-sm text-base-content/70">Referencia</dt><dd class="font-data"><?= esc($statement['referencia']) ?></dd></div><div><dt class="text-sm text-base-content/70">Fecha bancaria</dt><dd class="font-data"><?= esc($statement['fecha']) ?></dd></div></dl>
<p class="mt-4 rounded-field bg-base-200/70 p-3 text-sm"><?= esc($statement['observacion'] ?: 'Sin observaciones registradas.') ?></p><?php if ($statement['pago_id']): ?><div class="card-actions mt-4"><a class="btn" href="<?= site_url('pagos/' . (int) $statement['pago_id']) ?>">Abrir cobro #<?= (int) $statement['pago_id'] ?></a></div><?php endif ?></div></section>

<div class="mt-6 grid gap-6 lg:grid-cols-12"><section class="card card-border bg-base-100 lg:col-span-5"><div class="card-body"><h3 class="card-title">Evidencia</h3><?php if (!$statement['files']): ?><p class="text-sm text-base-content/70">No se adjuntó archivo.</p><?php else: ?><ul class="list"><?php foreach ($statement['files'] as $file): ?><li class="list-row"><i data-lucide="paperclip" class="icon" aria-hidden="true"></i><div class="list-col-grow"><p class="font-medium"><?= esc($file['nombre_original']) ?></p><p class="text-xs text-base-content/70"><?= number_format((int) $file['tamano_bytes'] / 1024, 1) ?> KB</p></div><a class="btn btn-sm" href="<?= site_url('reportes-pago/archivos/' . (int) $file['id']) ?>">Descargar</a></li><?php endforeach ?></ul><?php endif ?></div></section>
<section class="card card-border bg-base-100 lg:col-span-7"><div class="card-body"><h3 class="card-title">Conciliación</h3>
<?php if ($statement['cliente_id'] === null && $canIdentify): ?><p class="text-sm text-base-content/70">Identifica primero al titular económico. Esta acción todavía no crea un cobro.</p><form class="mt-4 grid gap-3 sm:grid-cols-[1fr_auto]" method="post" action="<?= site_url('ingresos-bancarios/' . (int) $statement['id'] . '/identificar') ?>"><?= csrf_field() ?><input type="hidden" name="idempotency_key" value="<?= esc($identifyKey, 'attr') ?>"><select class="select w-full" name="cliente_id" required data-client-select data-source="<?= site_url('clientes/datos') ?>"><option value="">Buscar cliente</option></select><button class="btn btn-primary" type="submit">Identificar</button></form>
<?php elseif ($final): ?><div class="alert alert-success alert-soft"><i data-lucide="badge-check" class="icon" aria-hidden="true"></i><span>Este comprobante ya está conciliado. El cobro queda disponible hasta que se distribuya a cuotas; cualquier corrección debe realizarse desde el cobro vinculado.</span></div>
<?php elseif ($canReview): ?><form method="post" action="<?= site_url('reportes-pago/' . (int) $statement['id'] . '/revisiones') ?>" class="grid gap-3"><?= csrf_field() ?><input type="hidden" name="idempotency_key" value="<?= esc($idempotencyKey, 'attr') ?>"><label class="form-field"><span>Decisión</span><select class="select w-full" name="decision" required><?php if ($statement['estado'] === 'Rechazado'): ?><option value="REABIERTO">Reabrir para nueva revisión</option><?php else: ?><option value="APROBADO">Aprobar y crear cobro disponible</option><?php if ($statement['matches']): ?><option value="VINCULADO">Vincular con un cobro existente</option><?php endif ?><option value="RECHAZADO">Rechazar sin crear cobro</option><?php endif ?></select></label><?php if ($statement['matches']): ?><label class="form-field"><span>Cobro coincidente (solo al vincular)</span><select class="select w-full" name="pago_id"><option value="">Seleccionar</option><?php foreach ($statement['matches'] as $match): ?><option value="<?= (int) $match['id'] ?>">#<?= (int) $match['id'] ?> · $<?= number_format((float) $match['importe'], 2) ?> · <?= esc($match['fecha']) ?> · <?= esc($match['referencia']) ?></option><?php endforeach ?></select></label><?php endif ?><label class="form-field"><span>Motivo y evidencia de revisión</span><textarea class="textarea w-full" name="notas" minlength="10" maxlength="500" required rows="3" placeholder="Explica cómo verificaste el ingreso"><?= esc(old('notas', '')) ?></textarea></label><p class="text-xs text-base-content/70">Aprobar confirma el dinero recibido y emite recibo; la aplicación a cuotas se realiza después desde el detalle del cobro.</p><div class="card-actions justify-end"><button class="btn btn-primary" type="submit" data-confirm="Confirma que comparaste cuenta, importe, fecha, referencia y evidencia.">Guardar decisión</button></div></form>
<?php else: ?><p class="text-sm text-base-content/70">No tienes permiso para conciliar este comprobante.</p><?php endif ?>
</div></section></div>

<section class="card card-border mt-6 bg-base-100"><div class="card-body"><h3 class="card-title">Historial de revisiones</h3><?php if (!$statement['reviews']): ?><p class="text-sm text-base-content/70">Todavía no existen revisiones.</p><?php else: ?><div class="overflow-x-auto"><table class="table"><thead><tr><th>Revisión</th><th>Resultado</th><th>Responsable</th><th>Fecha</th><th>Notas</th></tr></thead><tbody><?php foreach ($statement['reviews'] as $review): ?><tr><th class="font-data">#<?= (int) $review['revision'] ?></th><td><span class="badge <?= $statusClass((string) $review['resultado_label']) ?>"><?= esc($review['resultado_label']) ?></span></td><td><?= esc($review['revisor']) ?></td><td class="font-data"><?= esc($review['registrada_en']) ?></td><td><?= esc($review['notas']) ?></td></tr><?php endforeach ?></tbody></table></div><?php endif ?></div></section>

<?php elseif ($mode === 'unknown'): ?>
<section class="card card-border bg-base-100"><div class="card-body"><h2 class="card-title">Ingresos sin identificar</h2><p class="text-sm text-base-content/70">Asignar un cliente no confirma el ingreso ni reduce su deuda.</p><?php if (!$rows): ?><?= view('partials/empty_state', ['icon' => 'badge-check', 'title' => 'Sin casos pendientes', 'description' => 'No hay ingresos sin titular económico.'], ['saveData' => false]) ?><?php else: ?><div class="overflow-x-auto"><table class="table"><thead><tr><th>Comprobante</th><th>Cuenta</th><th>Monto</th><th>Fecha</th><th>Cliente</th></tr></thead><tbody><?php foreach ($rows as $row): ?><tr><th class="font-data">#<?= (int) $row['id'] ?></th><td><?= esc($row['origen']) ?></td><td class="font-data">$<?= number_format((float) $row['monto'], 2) ?></td><td class="font-data"><?= esc($row['fecha']) ?></td><td><form class="flex min-w-80 gap-2" method="post" action="<?= site_url('ingresos-bancarios/' . (int) $row['id'] . '/identificar') ?>"><?= csrf_field() ?><input type="hidden" name="idempotency_key" value="<?= esc($row['idempotency_key'], 'attr') ?>"><select class="select min-w-56 flex-1" name="cliente_id" required data-client-select data-source="<?= site_url('clientes/datos') ?>"><option value="">Buscar cliente</option></select><button class="btn" type="submit">Identificar</button></form></td></tr><?php endforeach ?></tbody></table></div><?php endif ?></div></section>

<?php else: ?>
<?php $filters = $filters ?? ['q' => '', 'estado' => '']; ?>
<form class="card card-border mb-6 bg-base-100" method="get" action="<?= site_url('reportes-pago') ?>"><div class="card-body gap-4 sm:flex-row sm:items-end"><label class="form-field min-w-0 flex-1"><span>Buscar</span><input class="input w-full" type="search" name="q" maxlength="100" value="<?= esc($filters['q'], 'attr') ?>" placeholder="Cliente o referencia"></label><label class="form-field w-full sm:w-56"><span>Estado</span><select class="select w-full" name="estado"><option value="">Todos</option><?php foreach (['PENDIENTE' => 'Pendiente', 'APROBADO' => 'Aprobado', 'VINCULADO' => 'Vinculado', 'RECHAZADO' => 'Rechazado', 'REABIERTO' => 'Reabierto'] as $value => $label): ?><option value="<?= $value ?>" <?= $filters['estado'] === $value ? 'selected' : '' ?>><?= $label ?></option><?php endforeach ?></select></label><div class="card-actions"><a class="btn" href="<?= site_url('reportes-pago') ?>">Limpiar</a><button class="btn btn-primary" type="submit">Filtrar</button></div></div></form>
<section class="stats stats-vertical w-full border border-base-300 bg-base-100 md:stats-horizontal" aria-label="Resumen de comprobantes"><div class="stat"><div class="stat-title">Pendientes</div><div class="stat-value font-data text-3xl"><?= (int) $totals['Pendiente'] ?></div></div><div class="stat"><div class="stat-title">Conciliados</div><div class="stat-value font-data text-3xl"><?= (int) $totals['Aprobado'] + (int) $totals['Vinculado'] ?></div></div><div class="stat"><div class="stat-title">Rechazados</div><div class="stat-value font-data text-3xl"><?= (int) $totals['Rechazado'] ?></div></div></section>
<section class="card card-border mt-6 bg-base-100"><div class="card-body p-0"><?php if (!$rows): ?><?= view('partials/empty_state', ['icon' => 'inbox', 'title' => 'Sin comprobantes', 'description' => 'No hay registros que coincidan con los filtros.', 'action' => ['label' => 'Registrar comprobante', 'url' => site_url('reportes-pago/nuevo')]], ['saveData' => false]) ?><?php else: ?><div class="overflow-x-auto"><table class="table"><caption class="sr-only">Bandeja de comprobantes bancarios</caption><thead><tr><th>Comprobante</th><th>Cliente</th><th>Cuenta</th><th>Fecha</th><th>Monto</th><th>Estado</th><th><span class="sr-only">Acción</span></th></tr></thead><tbody><?php foreach ($rows as $row): ?><tr><th class="font-data">#<?= (int) $row['id'] ?></th><td><?= esc($row['cliente']) ?></td><td><?= esc($row['banco'] . ' · ' . $row['cuenta']) ?></td><td class="font-data"><?= esc($row['fecha']) ?></td><td class="font-data">$<?= number_format((float) $row['monto'], 2) ?></td><td><span class="badge <?= $statusClass((string) $row['estado']) ?>"><?= esc($row['estado']) ?></span></td><td><a class="btn btn-sm" href="<?= site_url('reportes-pago/' . (int) $row['id']) ?>">Abrir</a></td></tr><?php endforeach ?></tbody></table></div><?php endif ?></div></section>
<?php endif ?>

<?= $this->endSection() ?>
