<?= $this->extend('layouts/app') ?>
<?= $this->section('content') ?>

<?= view('partials/page_header', ['context' => 'Sesión actual', 'title' => $title, 'description' => $description], ['saveData' => false]) ?>

<div class="grid gap-6 lg:grid-cols-12">
    <section class="card card-border bg-base-100 lg:col-span-7" aria-labelledby="identity-title"><div class="card-body"><div class="flex flex-wrap items-center justify-between gap-3"><h2 id="identity-title" class="card-title">Identidad</h2><span class="badge <?= $account['active'] ? 'badge-success badge-soft' : 'badge-error badge-soft' ?>"><?= $account['active'] ? 'Cuenta activa' : 'Cuenta restringida' ?></span></div><dl class="mt-4 grid gap-5 sm:grid-cols-2"><div><dt class="text-sm text-base-content/70">Usuario</dt><dd class="mt-1 break-words font-semibold"><?= esc($account['username']) ?></dd></div><div><dt class="text-sm text-base-content/70">Correo</dt><dd class="mt-1 break-words"><?= esc($account['email'] ?: 'No informado') ?></dd></div><div><dt class="text-sm text-base-content/70">Identificador interno</dt><dd class="font-data mt-1">#<?= $account['id'] ?></dd></div><div><dt class="text-sm text-base-content/70">Función</dt><dd class="mt-1"><?= esc(implode(', ', $account['groups']) ?: 'Sin función') ?></dd></div></dl></div></section>
    <aside class="card card-border bg-base-100 lg:col-span-5" aria-labelledby="permissions-title"><div class="card-body"><h2 id="permissions-title" class="card-title">Permisos directos</h2><p class="text-sm text-base-content/70">Además de los permisos heredados por tu función.</p><?php if (!$account['permissions']): ?><p class="mt-3">No tienes permisos individuales asignados.</p><?php else: ?><ul class="mt-3 flex flex-wrap gap-2" aria-label="Permisos individuales"><?php foreach ($account['permissions'] as $permission): ?><li><span class="badge badge-ghost font-data"><?= esc($permission) ?></span></li><?php endforeach ?></ul><?php endif ?></div></aside>
</div>

<?php $errors = session('errors') ?? []; ?>
<?php if ($errors): ?><div id="form-errors" class="alert alert-error mt-8" role="alert" tabindex="-1"><i data-lucide="circle-alert" class="icon" aria-hidden="true"></i><div><h2 class="font-semibold">No se guardaron los cambios</h2><ul class="mt-1 list-disc pl-5"><?php foreach ($errors as $key => $error): ?><li><a class="underline" href="#<?= esc((string) $key, 'attr') ?>"><?= esc($error) ?></a></li><?php endforeach ?></ul></div></div><?php endif ?>

<div class="mt-8 grid gap-6 lg:grid-cols-2">
    <form method="post" action="<?= site_url('mi-cuenta') ?>" class="card card-border bg-base-100"><div class="card-body"><?= csrf_field() ?><fieldset class="fieldset"><legend class="fieldset-legend text-lg">Actualizar identidad</legend><label class="fieldset"><span class="fieldset-legend">Nombre de usuario</span><input id="username" class="input w-full" name="username" value="<?= esc(old('username', $account['username']), 'attr') ?>" required maxlength="30" autocomplete="username"><?php if (isset($errors['username'])): ?><span class="label text-error" id="username-error"><?= esc($errors['username']) ?></span><?php endif ?></label><label class="fieldset"><span class="fieldset-legend">Correo electrónico</span><input id="email" class="input w-full" type="email" name="email" value="<?= esc(old('email', $account['email']), 'attr') ?>" required maxlength="254" autocomplete="email"><?php if (isset($errors['email'])): ?><span class="label text-error" id="email-error"><?= esc($errors['email']) ?></span><?php endif ?></label></fieldset><div class="card-actions mt-3 justify-end"><button class="btn btn-primary" type="submit">Guardar mis datos</button></div></div></form>
    <form method="post" action="<?= site_url('mi-cuenta/contrasena') ?>" class="card card-border bg-base-100"><div class="card-body"><?= csrf_field() ?><fieldset class="fieldset"><legend class="fieldset-legend text-lg">Cambiar contraseña</legend><label class="fieldset"><span class="fieldset-legend">Contraseña actual</span><input id="current_password" class="input w-full" type="password" name="current_password" required autocomplete="current-password"><?php if (isset($errors['current_password'])): ?><span class="label text-error" id="current-password-error"><?= esc($errors['current_password']) ?></span><?php endif ?></label><label class="fieldset"><span class="fieldset-legend">Nueva contraseña</span><input id="password" class="input w-full" type="password" name="password" required minlength="12" autocomplete="new-password"></label><label class="fieldset"><span class="fieldset-legend">Repetir nueva contraseña</span><input id="password_confirm" class="input w-full" type="password" name="password_confirm" required minlength="12" autocomplete="new-password"></label></fieldset><div class="card-actions mt-3 justify-end"><button class="btn" type="submit">Cambiar contraseña</button></div></div></form>
</div>

<?= $this->endSection() ?>
